# Generated by Django 4.2 on 2024-04-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_plan_servicer_store_service_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='serviceeable',
            new_name='serviceable',
        ),
    ]
