# Generated by Django 4.2 on 2024-09-10 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customer_service_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='total',
            new_name='total_cost',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='servicer',
        ),
        migrations.RemoveField(
            model_name='servicer',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bill_for',
        ),
        migrations.AddField(
            model_name='customer',
            name='zipCode',
            field=models.CharField(default=98, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicer',
            name='rev_share',
            field=models.CharField(default=0.1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='Default Description', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='service_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5)),
                ('servicer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_code', to='app.servicer')),
            ],
        ),
    ]
