# Generated by Django 4.2 on 2024-09-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_total_transaction_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
            preserve_default=False,
        ),
    ]
